line-length = 100
indent-width = 4
target-version = "py311"

[format]
line-ending = "lf"

[lint]
ignore = [
  "F401",
]

extend-select = [
  "I",
]

[lint.isort]
case-sensitive = true
no-lines-before = ["local-folder"]
relative-imports-order = "closest-to-furthest"
lines-after-imports = 2
known-first-party = [
  "claudebox",
  "claudebox_cli",
  "claudebox_container_api",
  "claudebox_daemon",
  "claudebox_frontend"
]
