"""AgentSession - Protocol every runtime adapter satisfies."""

import asyncio
from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable

from .catalogs import ContextUsage, EffortLevel, Model, PermissionMode, Skill
from .config import RuntimeCapabilities
from .events import AgentEvent


@runtime_checkable
class AgentSession(Protocol):
    """Runtime-neutral interface implemented by every adapter."""

    runtime_name: str

    ready: asyncio.Event

    @property
    def capabilities(self) -> RuntimeCapabilities: ...

    async def connect(self) -> None: ...

    async def disconnect(self) -> None: ...

    async def query(self, prompt: str | list[dict]) -> None: ...

    async def interrupt(self) -> None: ...

    async def set_model(self, model: str | None = None) -> None: ...

    async def set_permission_mode(self, mode: str) -> None: ...

    async def set_effort_level(self, level: str) -> None: ...

    async def reconnect_mcp_server(self, server_name: str) -> None: ...

    async def toggle_mcp_server(self, server_name: str, enabled: bool) -> None: ...

    async def get_mcp_status(self) -> dict: ...

    async def get_context_usage(self) -> ContextUsage | None: ...

    def receive_events(self) -> AsyncIterator[AgentEvent]: ...

    def get_models(self) -> list[Model]: ...

    def get_effort_levels(self) -> list[EffortLevel]: ...

    def get_permission_modes(self) -> list[PermissionMode]: ...

    def get_skills(self) -> list[Skill]: ...
